import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideSetup from '../components/ClientSideSetup'; // 올바른 경로로 수정

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideSetup /> {/* 클라이언트 사이드 설정 컴포넌트를 추가 */}
        {children}
      </body>
    </html>
  );
}
